---
- name: Test Nutanix Connectivity
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Query Prism Central cluster information
      nutanix.ncp.ntnx_clusters_info:
        nutanix_host: "{{ nutanix_host }}"
        nutanix_username: "{{ nutanix_username }}"
        nutanix_password: "{{ nutanix_password }}"
        validate_certs: false
      register: cluster_info
      no_log: true

    - name: Display cluster names
      debug:
        msg: "Cluster Name: {{ item.status.name }}"
      loop: "{{ cluster_info.response.entities }}"
